# Generated by Django 2.0.5 on 2018-06-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prouct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('productType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washerName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WasherQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_order.Prouct')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_order.Washer')),
            ],
        ),
    ]
