# Generated by Django 2.0.6 on 2018-06-18 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_order', '0002_auto_20180617_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='washer',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='washerqueue',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washer',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washerqueue',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='washerqueue',
            name='product',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='washerqueue',
            name='volume',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='washerqueue',
            name='washer',
            field=models.CharField(max_length=30),
        ),
    ]
